--if data.raw.radar["scanning-radar"] then
	--data.raw.radar["scanning-radar"].energy_usage = multiply_number_unit(data.raw.radar["scanning-radar"].energy_usage, 0.5)
	--data.raw.radar["scanning-radar"].energy_per_sector = multiply_number_unit(data.raw.radar["scanning-radar"].energy_per_sector, 0.5)
	--data.raw.radar["scanning-radar"].energy_per_nearby_scan = multiply_number_unit(data.raw.radar["scanning-radar"].energy_per_nearby_scan, 0.5)
	--data.raw.pump["scanning-radar-connection"].energy_usage = multiply_number_unit(data.raw.pump["scanning-radar-connection"].energy_usage, 0.5)
--end